Update Japanese locale
rxhanson/Rectangle pull request #508
Opened 2021-07-05 12:38 UTC by hiro0218

2021-07-05 17:31 UTC, rxhanson commented
Thanks!

If you don't mind, would you like to translate the following lines as well? That would complete the missing translations for this round.

> /* Class = "NSTextFieldCell"; title = "First Three Fourths"; ObjectID = "T9Z-QF-gwc"; */
> "T9Z-QF-gwc.title" = "";
> 
> /* Class = "NSTextFieldCell"; title = "Last Three Fourths"; ObjectID = "nwX-h6-fwm"; */
> "nwX-h6-fwm.title" = "";
> 
> /* Class = "NSButtonCell"; title = "Import"; ObjectID = "RgZ-Jw-XQZ"; */
> "RgZ-Jw-XQZ.title" = "";
> 
> /* Class = "NSButtonCell"; title = "Export"; ObjectID = "IO3-Hi-7gC"; */
> "IO3-Hi-7gC.title" = "";

If not, that's ok and I will go ahead and merge what's in this PR.

2021-07-06 04:19 UTC, hiro0218 commented
@rxhanson 
I've added translation support. Please check it out. 😉

2021-07-06 07:37 UTC, ryonakano requested changes
@hiro0218 Thank you for completing Japanese translation! I reviewed your translation suggestion.

2021-07-06 07:37 UTC, ryonakano commented on Rectangle/ja.lproj/Main.strings
> +"T9Z-QF-gwc.title" = "4/3にして左寄せ";
```suggestion
"T9Z-QF-gwc.title" = "3/4にして左寄せ";
```

画面の4分の3に分割するということなので、"3/4"だと思います。

2021-07-06 07:37 UTC, ryonakano commented on Rectangle/ja.lproj/Main.strings
> +"nwX-h6-fwm.title" = "4/3にして右寄せ";
```suggestion
"nwX-h6-fwm.title" = "3/4にして右寄せ";
```

2021-07-06 07:37 UTC, ryonakano commented on Rectangle/ja.lproj/Main.strings
> +"Pbz-DF-hgG.title" = "ディスプレイ上のウィンドウに沿ってカーソルを移動する";
```suggestion
"Pbz-DF-hgG.title" = "別ディスプレイへのウィンドウ移動時にカーソルも一緒に移動させる";
```

「ウィンドウに沿って」だと、意味が伝わりにくいと思います。[こちらの記事](https://applech2.com/archives/20210704-rectangle-for-mac-move-cursor-across-dispalys.html)もご覧ください。

2021-07-06 13:01 UTC, hiro0218 commented on Rectangle/ja.lproj/Main.strings
> +"T9Z-QF-gwc.title" = "4/3にして左寄せ";
「4分の3」を思い浮かべて「4/3」としてしまいました。訂正ありがとうございます。

2021-07-06 13:02 UTC, hiro0218 commented on Rectangle/ja.lproj/Main.strings
> +"Pbz-DF-hgG.title" = "ディスプレイ上のウィンドウに沿ってカーソルを移動する";
採用させて頂きます🙏

2021-07-06 13:03 UTC, hiro0218 commented
@ryonakano Thank you for your review!

2021-07-06 13:49 UTC, ryonakano approved these changes
LGTM!

2021-07-06 17:15 UTC, merged

2021-07-06 17:15 UTC, rxhanson commented
Great, thanks!